name: Build debug APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.4'

      - name: Download libv2ray.aar from AndroidLibXrayLite's GitHub Release
        uses: robinraju/release-downloader@v1
        with:
          repository: '2dust/AndroidLibXrayLite'
          latest: true
          fileName: 'libv2ray.aar'
          out-file-path: 'app/libs'

      - name: Build debug APK
        run: gradle assembleDebug --stacktrace

      - name: Upload APK as a build artifact
        uses: actions/upload-artifact@v4
        with:
          name: v2ray-config-app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
